/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bebasrapi;

/**
 *
 * @author understd
 */
public class ArrayForm extends javax.swing.JFrame {

    /**
     * Creates new form ArrayForm
     */
    public ArrayForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jconadokt = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jtxtnama = new javax.swing.JTextField();
        jtxtalamat = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jtxtusia = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jtxtjenis = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jtxtgol = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jtxtstatus = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jtxtkewar = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jtxtwaktu = new javax.swing.JTextField();
        jtxtspesial = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Pemilihan Dokter");
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Pemilihan Dokter");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(50, 20, 400, 40);

        jconadokt.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "----------== PILIH ITEM", "DR. Ahmad Subagyo", "DR. Anshor Ibrohim", "DR. Siti Nur Zubaedah" }));
        jconadokt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jconadoktActionPerformed(evt);
            }
        });
        getContentPane().add(jconadokt);
        jconadokt.setBounds(130, 90, 310, 26);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Data"));
        jPanel1.setLayout(null);

        jLabel2.setText("Nama");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(20, 30, 140, 20);
        jPanel1.add(jtxtnama);
        jtxtnama.setBounds(170, 30, 230, 24);
        jPanel1.add(jtxtalamat);
        jtxtalamat.setBounds(170, 60, 230, 24);

        jLabel4.setText("Alamat");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(20, 60, 140, 20);
        jPanel1.add(jtxtusia);
        jtxtusia.setBounds(170, 90, 230, 24);

        jLabel5.setText("Usia");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(20, 90, 140, 20);
        jPanel1.add(jtxtjenis);
        jtxtjenis.setBounds(170, 120, 230, 24);

        jLabel6.setText("Jenis Kelamin");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(20, 120, 140, 20);

        jLabel7.setText("Goldar");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(20, 150, 140, 20);
        jPanel1.add(jtxtgol);
        jtxtgol.setBounds(170, 150, 230, 24);

        jLabel8.setText("Status");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(20, 180, 140, 20);
        jPanel1.add(jtxtstatus);
        jtxtstatus.setBounds(170, 180, 230, 24);

        jLabel9.setText("Kewarganegaraan");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(20, 210, 140, 20);
        jPanel1.add(jtxtkewar);
        jtxtkewar.setBounds(170, 210, 230, 24);

        jLabel10.setText("Waktu Praktek");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(20, 240, 140, 20);
        jPanel1.add(jtxtwaktu);
        jtxtwaktu.setBounds(170, 240, 230, 24);
        jPanel1.add(jtxtspesial);
        jtxtspesial.setBounds(170, 270, 230, 24);

        jLabel11.setText("Spesialis");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(20, 270, 140, 20);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(20, 130, 430, 310);

        jLabel3.setText("Pilih Dokter");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(30, 90, 90, 20);

        setSize(new java.awt.Dimension(484, 503));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jconadoktActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jconadoktActionPerformed
        // TODO add your handling code here:
        if(jconadokt.getSelectedItem().equals("DR. Ahmad Subagyo")){
            jtxtnama.setText("DR. Ahmad Subagyo");
            jtxtalamat.setText("Jl. Surabaya 16, Malang");
            jtxtusia.setText("23 Tahun");
            jtxtjenis.setText("Laki-Laki");
            jtxtgol.setText("B+");
            jtxtstatus.setText("Belum Menikah");
            jtxtkewar.setText("Indonesia");
            jtxtspesial.setText("Dokter Spesialis Syarap");
            jtxtwaktu.setText(" Pagi (07.00-15.00)");
        }else if(jconadokt.getSelectedItem().equals("DR. Anshor Ibrohim")){
            jtxtnama.setText("DR. Anshor Ibrohim");
            jtxtalamat.setText("Jl. Veteran 3, Malang");
            jtxtusia.setText("20 Tahun");
            jtxtjenis.setText("Perempuan");
            jtxtgol.setText("B-");
            jtxtstatus.setText("Belum Menikah");
        }else if(jconadokt.getSelectedItem().equals("DR. Siti Nur Zubaedah")){
            jtxtnama.setText("DR. Siti Nur Zubaedah");
            jtxtalamat.setText("Jl. Sekeres 45, Malang");
            jtxtusia.setText("34 Tahun");
            jtxtjenis.setText("Perempuan");
            jtxtgol.setText("O");
            jtxtstatus.setText("Belum Menikah");
        }
    }//GEN-LAST:event_jconadoktActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ArrayForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ArrayForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ArrayForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ArrayForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ArrayForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JComboBox<String> jconadokt;
    private javax.swing.JTextField jtxtalamat;
    private javax.swing.JTextField jtxtgol;
    private javax.swing.JTextField jtxtjenis;
    private javax.swing.JTextField jtxtkewar;
    private javax.swing.JTextField jtxtnama;
    private javax.swing.JTextField jtxtspesial;
    private javax.swing.JTextField jtxtstatus;
    private javax.swing.JTextField jtxtusia;
    private javax.swing.JTextField jtxtwaktu;
    // End of variables declaration//GEN-END:variables
}
